apiVersion: v1
kind: Pod
metadata:
  name: python-microservice
  namespace: tech.prod
spec:
  containers:
  - name: python-microservice
    image: python:3.8-slim
    ports:
    - containerPort: 5000
    command: ["python"]
    args: ["-u", "app.py"]
    resources:
      limits:
        memory: "3Gi"
